# Generated by Django 4.1.7 on 2023-04-14 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_datatype_created_by_alter_datatype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_types_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
