# Generated by Django 4.1.7 on 2023-04-15 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_datatype_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathoperator',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='math_operators_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mathoperator',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
